env: dev

server:
  port: 3000
  global-prefix: api

database:
  type: mysql
  url: ${DATABASE_URL}

redis:
  host: localhost
  port: 6379

jwt:
  key-id: izayoi
  expires-in: 2d

throttler:
  ttl: 60
  limit: 10

swagger:
  title: Another Real World
  description: The real-world API
  version: '1.0'
  path: swagger
